changed company name and added new logo

diff --git a/configfiles/buildpsecdevsecops.yml b/configfiles/buildpsecdevsecops.yml
--- a/configfiles/buildpsecdevsecops.yml
+++ b/configfiles/buildpsecdevsecops.yml
@@ -31,9 +31,9 @@ phases:
         docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py  -t http://3.12.136.142 -c configfiles/tests.conf -d > report.txt
         if grep -q -E 'FAIL-NEW: [1-9]+' report.txt; then # check if any new failures were detected
           aws s3 cp report.txt s3://devopsbucketstorage/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
-          echo "BUILD FAILED AND THE LAST KNOWN STABLE STATE WAS RESROTED BECAUSE A CRITICAL VULNERABILITY WAS DETECTED. PLEASE LOOK AT THE LATEST REPORT FOR FURTHER ANALYSIS"
+          echo "BUILD FAILED AND THE LAST KNOWN STABLE STATE WAS RESTORED BECAUSE A CRITICAL VULNERABILITY WAS DETECTED. PLEASE LOOK AT THE LATEST REPORT FOR FURTHER ANALYSIS"
           ssh -i DevOps_Key.pem ubuntu@3.12.136.142 'sudo ./implement_rollback.sh'
-          exit 0
+          exit 1
         else
           aws s3 cp report.txt s3://devopsbucketstorage/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
           echo "BUILD WAS SUCCESFUL and all security standards are met and no critical vulnerabilities were detected"
