added owasp testing

diff --git a/configfiles/buildpsecdevsecops.yml b/configfiles/buildpsecdevsecops.yml
--- a/configfiles/buildpsecdevsecops.yml
+++ b/configfiles/buildpsecdevsecops.yml
@@ -30,10 +30,14 @@ phases:
         set +e # disable the 'exit immediately on error' option
         docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py  -t http://3.12.136.142 -c configfiles/tests.conf -d > report.txt
         if grep -q 'FAIL-NEW: 1' report.txt; then # check if any new failures were detected 
-          exit 0
+          aws s3 cp report.txt s3://devopsbucketstorage/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
+          echo "BUILD FAILED BECAUSE A CRITICAL VULNERABILITY WAS DETECTED"
+          exit 1
         else
-          exit 1 
+          aws s3 cp report.txt s3://devopsbucketstorage/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
+          echo "BUILD WAS SUCCESFUL and all security standards are met and no critical vulnerabilities were detected"
+          exit 0
         fi
         set -e 
-      - #ls  
-      - #aws s3 cp report.html s3://devopsbucketstorage/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").html
+
+      
